blank_issues_enabled: false

issue_templates:
  - name: "ğŸ› Bug Report"
    about: "File a bug report to help us improve."
    template: bug_report.md

  - name: "âœ¨ Feature Request"
    about: "Suggest an idea for this project."
    template: feature_request.md

  - name: "ğŸ”§ Chore or Maintenance Task"
    about: "Report a chore, refactor, or maintenance task."
    template: chore.md

  - name: "ğŸ“– Documentation Issue"
    about: "Report an error, typo, or unclear section in the documentation."
    template: docs_issue.md

contact_links:
  - name: "â“ Ask a Question or Get Help"
    url: https://github.com/josephchaouistannard/connect_four_flutter/discussions/new?category=q-a
    about: "This is the best place for questions, help requests, and discussions."

  - name: "ğŸ’¬ General Chat & Ideas"
    url: https://github.com/josephchaouistannard/connect_four_flutter/discussions
    about: "Please use our discussion board for general community chat and brainstorming."
